[project]
name = "dependencies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.31",
    "dotenv>=0.9.9",
    "opensearch-py>=2.8.0",
    "pandas>=2.2.3",
    "requests-aws4auth>=1.3.1",
]
