[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.25",
    "mcp[cli]>=1.6.0",
    "opensearch-py>=2.8.0",
    "requests-aws4auth>=1.3.1",
    "splunk-sdk>=2.1.0",
]
